<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks to truncate tables cleanly
        Schema::disableForeignKeyConstraints();
        MenuItem::truncate();
        Category::truncate();
        Schema::enableForeignKeyConstraints();

        $categories = [
            [
                'name'        => 'Special Combos',
                'slug'        => 'special_combo',
                'emoji'       => '🍱',
                'description' => 'Hearty combinations and thalis',
                'sort_order'  => 1,
            ],
            [
                'name'        => 'Chur Chur Naan',
                'slug'        => 'chur_chur_naan',
                'emoji'       => '🫓',
                'description' => 'Crispy Chur Chur Naan Combos with Dal Makhani or Paneer Lababdar',
                'sort_order'  => 2,
            ],
            [
                'name'        => 'Punjabi Sabji',
                'slug'        => 'punjabi_sabji',
                'emoji'       => '🍲',
                'description' => 'Delicious curries served with 2 Butter Roti (default)',
                'sort_order'  => 3,
            ],
            [
                'name'        => 'Sabji Combo',
                'slug'        => 'sabji_combo',
                'emoji'       => '🍛',
                'description' => 'Curry & Naan pairings',
                'sort_order'  => 4,
            ],
            [
                'name'        => 'Aloo Combo',
                'slug'        => 'aloo_combo',
                'emoji'       => '🥔',
                'description' => 'Delectable potato meals served with Roti/Puri & Chaas',
                'sort_order'  => 5,
            ],
            [
                'name'        => 'Rice Combo',
                'slug'        => 'rice_combo',
                'emoji'       => '🍚',
                'description' => 'Fragrant rice pairings served with Raita or Chaas',
                'sort_order'  => 6,
            ],
        ];

        foreach ($categories as $cat) {
            Category::create($cat);
        }

        $items = [
            // ===================== SPECIAL COMBOS =====================
            [
                'name'        => 'Amritsari Naan with Chole',
                'description' => 'Stuffed Naan with vegetables & Amritsari Punjabi Masala, served with Chutney, Chaas, Pickle & Onion.',
                'category'    => 'special_combo',
                'price'       => 149,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Amritsari Fix Thali',
                'description' => '2 Tandoori Roti, 1 Paneer Sabji, Dal Fry, Rice, Papad, Chaas.',
                'category'    => 'special_combo',
                'price'       => 189,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Special Punjabi Thali',
                'description' => '2 Tandoori Roti, 1 Paneer Sabji, 1 Veg Sabji/Chole, Dal Fry, Rice, Papad, Salad, Gulab Jamun, Chaas.',
                'category'    => 'special_combo',
                'price'       => 219,
                'prep_time'   => 20,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Delux Punjabi Thali',
                'description' => 'Paneer Butter Masala, Chana/Veg, Dal Makhani, 2 Butter Naan, Jeera Rice, Dal Fry, Salad, 2 Gulab Jamun, Chaas.',
                'category'    => 'special_combo',
                'price'       => 249,
                'prep_time'   => 20,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Butter Masala Thali',
                'description' => 'Paneer Butter Masala curry served with 1 Lachha Paratha and 2 Gulab Jamun.',
                'category'    => 'special_combo',
                'price'       => 159,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Amritsari Chana, Jeera Rice',
                'description' => 'Amritsari style spicy Chole served with hot Jeera Rice.',
                'category'    => 'special_combo',
                'price'       => 149,
                'prep_time'   => 12,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Dal Makhani, Rice',
                'description' => 'Rich creamy Dal Makhani served with hot steamed Basmati Rice.',
                'category'    => 'special_combo',
                'price'       => 169,
                'prep_time'   => 12,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626516145550-ac826b1db968?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Dal Tadka, Jeera Rice, 1 Chaas, Papad',
                'description' => 'A complete yellow dal meal served with Jeera Rice, refreshing Chaas, and crispy Papad.',
                'category'    => 'special_combo',
                'price'       => 179,
                'prep_time'   => 12,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Masala Khichadi, Curd',
                'description' => 'A comforting, mildly spiced Masala Khichadi served with fresh Curd.',
                'category'    => 'special_combo',
                'price'       => 149,
                'prep_time'   => 10,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Veg Khichadi, Curd',
                'description' => 'Healthy Khichadi loaded with seasonal vegetables, served with fresh Curd.',
                'category'    => 'special_combo',
                'price'       => 159,
                'prep_time'   => 10,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Chole Bhature & 2 Pcs',
                'description' => 'Authentic spicy Amritsari Chole served with 2 fluffy golden-fried Bhature.',
                'category'    => 'special_combo',
                'price'       => 129,
                'prep_time'   => 15,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Chana & 4 Puri',
                'description' => 'Tandoori spiced Chana curry served with 4 hot crispy wheat Puris.',
                'category'    => 'special_combo',
                'price'       => 119,
                'prep_time'   => 12,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=800&q=80'],
            ],

            // ===================== CHUR CHUR NAAN =====================
            [
                'name'        => 'Chur Chur Naan (with Dal Makhani)',
                'description' => 'Crushed crispy tandoori stuffed naan served with rich Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 159,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Crushed crispy tandoori stuffed naan served with sweet and tangy Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 169,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Aloo Chur Chur Naan (with Dal Makhani)',
                'description' => 'Crispy potato stuffed crushed naan served with Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 179,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Aloo Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Crispy potato stuffed crushed naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 189,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Mix Veg Chur Chur Naan (with Dal Makhani)',
                'description' => 'Mixed vegetable stuffed crispy crushed naan served with Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 189,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Mix Veg Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Mixed vegetable stuffed crispy crushed naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 199,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Chur Chur Naan (with Dal Makhani)',
                'description' => 'Spiced paneer stuffed crispy crushed naan served with Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 199,
                'prep_time'   => 15,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Spiced paneer stuffed crispy crushed naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 209,
                'prep_time'   => 15,
                'rating'      => 4.9,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Cheese Paneer Chur Chur Naan (with Dal Makhani)',
                'description' => 'Melted cheese and paneer stuffed crushed tandoori naan served with Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 209,
                'prep_time'   => 15,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Cheese Paneer Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Melted cheese and paneer stuffed crushed tandoori naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 219,
                'prep_time'   => 15,
                'rating'      => 4.9,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Garlic Paneer Chur Chur Naan (with Dal Makhani)',
                'description' => 'Garlicky tandoori paneer chur chur naan served with creamy Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 199,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Garlic Paneer Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Garlicky tandoori paneer chur chur naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 209,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1585938338392-50a59970d8ee?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Aloo Pyaaz Chur Chur Naan (with Dal Makhani)',
                'description' => 'Spiced potato and onion stuffed crispy crushed naan served with Dal Makhani.',
                'category'    => 'chur_chur_naan',
                'price'       => 219,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Aloo Pyaaz Chur Chur Naan (with Paneer Lababdar)',
                'description' => 'Spiced potato and onion stuffed crispy crushed naan served with Paneer Lababdar.',
                'category'    => 'chur_chur_naan',
                'price'       => 229,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80'],
            ],

            // ===================== PUNJABI SABJI =====================
            [
                'name'        => 'Dal Makhani Combo (with 2 Butter Roti)',
                'description' => 'Slow-cooked rich creamy black lentils served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 149,
                'prep_time'   => 15,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1626516145550-ac826b1db968?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Veg Kolhapuri Combo (with 2 Butter Roti)',
                'description' => 'Spicy mixed vegetable Kolhapuri curry served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 159,
                'prep_time'   => 15,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Tikka Masala Combo (with 2 Butter Roti)',
                'description' => 'Smoky tandoori Paneer Tikka in rich tomato gravy served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 169,
                'prep_time'   => 18,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Butter Masala Combo (with 2 Butter Roti)',
                'description' => 'Cottage cheese cubes in creamy tomato-cashew gravy served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 179,
                'prep_time'   => 18,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Paneer Kadai Combo (with 2 Butter Roti)',
                'description' => 'Paneer cubes and capsicum in spicy kadai gravy served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 169,
                'prep_time'   => 18,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Shahi Paneer Combo (with 2 Butter Roti)',
                'description' => 'Royal paneer cooked in mild creamy saffron gravy served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 169,
                'prep_time'   => 18,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Sp. Amritsari Paneer Combo (with 2 Butter Roti)',
                'description' => 'Special Amritsari paneer cooked with unique spice blend served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 199,
                'prep_time'   => 18,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Cheese Angoori Combo (with 2 Butter Roti)',
                'description' => 'Rich sweet-tangy curry loaded with cheese balls served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 209,
                'prep_time'   => 18,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Veg Handi Combo (with 2 Butter Roti)',
                'description' => 'Seasonal mix vegetables cooked in rich handi gravy served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 159,
                'prep_time'   => 15,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Mix Veg Combo (with 2 Butter Roti)',
                'description' => 'Fresh seasonal mixed vegetable curry served with 2 soft Butter Rotis.',
                'category'    => 'punjabi_sabji',
                'price'       => 129,
                'prep_time'   => 15,
                'rating'      => 4.5,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],

            // ===================== SABJI COMBO =====================
            [
                'name'        => 'Kaju Curry with Hariyali Naan',
                'description' => 'Creamy roasted cashew curry paired with a fresh green Hariyali Naan.',
                'category'    => 'sabji_combo',
                'price'       => 219,
                'prep_time'   => 18,
                'rating'      => 4.8,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Cheese Butter Masala with Chur Chur Naan',
                'description' => 'Decadent Cheese Butter Masala curry served with a crispy Chur Chur Naan.',
                'category'    => 'sabji_combo',
                'price'       => 239,
                'prep_time'   => 20,
                'rating'      => 4.9,
                'is_featured' => true,
                'image'       => ['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Amritsari Paneer with Garlic Naan',
                'description' => 'Rich spicy Amritsari Paneer curry paired with a hot garlicky tandoori Garlic Naan.',
                'category'    => 'sabji_combo',
                'price'       => 219,
                'prep_time'   => 18,
                'rating'      => 4.8,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80'],
            ],

            // ===================== ALOO COMBO =====================
            [
                'name'        => 'Jeera Aloo + 3 Tawa Roti + 1 Chaas',
                'description' => 'Dry spiced cumin potatoes served with 3 Tawa Rotis and a glass of refreshing buttermilk.',
                'category'    => 'aloo_combo',
                'price'       => 149,
                'prep_time'   => 12,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Jeera Aloo + 4 Puri + 1 Chaas',
                'description' => 'Dry spiced cumin potatoes served with 4 wheat Puris and a glass of cold buttermilk.',
                'category'    => 'aloo_combo',
                'price'       => 149,
                'prep_time'   => 12,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Aloo Matar + 3 Tawa Roti + 1 Chaas',
                'description' => 'Tangy potato and green peas curry served with 3 Tawa Rotis and a glass of buttermilk.',
                'category'    => 'aloo_combo',
                'price'       => 149,
                'prep_time'   => 12,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80'],
            ],

            // ===================== RICE COMBO =====================
            [
                'name'        => 'Veg Pulao + Raita + Lachha Onion',
                'description' => 'Basmati rice cooked with garden fresh vegetables, served with chilled raita and onion salad.',
                'category'    => 'rice_combo',
                'price'       => 129,
                'prep_time'   => 15,
                'rating'      => 4.7,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Chana Pulao + Chaas',
                'description' => 'Healthy chickpea pulao served with a glass of spiced salted buttermilk.',
                'category'    => 'rice_combo',
                'price'       => 119,
                'prep_time'   => 15,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80'],
            ],
            [
                'name'        => 'Mag Pulao + Chaas',
                'description' => 'Traditional Moong bean pulao served with a glass of cold buttermilk.',
                'category'    => 'rice_combo',
                'price'       => 119,
                'prep_time'   => 15,
                'rating'      => 4.6,
                'is_featured' => false,
                'image'       => ['https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80'],
            ],
        ];

        foreach ($items as $item) {
            MenuItem::create($item);
        }
    }
}
